// SPDX-License-Identifier: MIT
// `em api generate | check` (MIL-237, promoted from the MIL-159 `em typespec` POC):
// generator scoping (public commands/events/views), the fixed public type table (R7), optional
// fields (`name?:`, R8), doc comments (never decorators), determinism, the golden
// examples/order-fulfillment contract, the committed examples/multi-model contracts, the
// additive/breaking classification (R8), the `check` CLI (current/stale/missing, --base against
// a real tmp git repo, a model absent at base), and the deprecated `em typespec` alias. The
// `@typespec/compiler` block at the bottom compiles generated text — skip-if-absent.
import { describe, it, expect } from "vitest";
import { spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "../src/pipeline.js";
import { buildApiContract, CONSUMER_TOLERANCE_SENTENCE } from "../src/emit/api.js";
import { buildExportDoc } from "../src/emit/json.js";
import { contractPathFor, diffSurfaces, generateContract, surfaceOf, sourceLabelFor } from "../src/cli/api.js";
import { API_CHECK_SCHEMA_VERSION } from "../src/emit/apiCheckJson.js";
import { PUBLIC_SCALAR_TYPES } from "../src/model/model.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const EXAMPLE_PATH = join(ROOT, "examples/order-fulfillment/order-fulfillment.em");
const MULTI = join(ROOT, "examples/multi-model");
const TSX = join(ROOT, "node_modules", "tsx", "dist", "cli.mjs");
const CLI = join(ROOT, "src", "cli.ts");

function em(args: string[], cwd: string) {
  const res = spawnSync(process.execPath, [TSX, CLI, ...args], { cwd, encoding: "utf8" });
  return { status: res.status, stdout: res.stdout, stderr: res.stderr };
}
function git(dir: string, ...args: string[]): string {
  const r = spawnSync("git", ["-c", "user.email=t@t.test", "-c", "user.name=t", "-C", dir, ...args], { encoding: "utf8" });
  if (r.status !== 0) throw new Error(`git ${args.join(" ")} failed: ${r.stderr}`);
  return r.stdout;
}

const generate = (src: string, path = "model.em") => {
  const { model, refs, diagnostics } = compile(src);
  return buildApiContract(model, refs, diagnostics, src, path);
};

describe("header", () => {
  it("is the fixed GENERATED line plus the source path — no source hash", () => {
    const src = `slice "S" {\n  command Do Thing\n}`;
    const { text } = generate(src, "some/path.em");
    expect(text.split("\n").slice(0, 2)).toEqual([
      "// GENERATED by em api generate — do not hand-edit.",
      "// Source: some/path.em",
    ]);
    expect(text).not.toMatch(/sha256|@versioned|@route|@get/);
  });

  it("an internal-only edit (non-public element, internal field) leaves the contract byte-identical", () => {
    const before = `slice "S" {
  ui Screen @Customer
  command Do public { a: string }
  event Done @D public { a: string }
  event Internal @D { x: Money }
}
`;
    const after = `slice "S" {
  ui Screen @Customer
  command Do public { a: string }
  event Done @D public { a: string }
  event Internal @D { x: Money, y: List<Whatever> }
  event Another Internal @D
}
# a comment
`;
    expect(generate(after, "m.em").text).toBe(generate(before, "m.em").text);
  });

  it("labels the source relative to the contract file's directory, so cwd never changes the text", () => {
    expect(sourceLabelFor("models/a/a.em", "models/a/contracts/a.tsp")).toBe("../a.em");
    expect(contractPathFor("models/a/a.em", "a")).toBe(join("models/a", "contracts", "a.tsp"));
  });
});

describe("scoping", () => {
  it("emits nothing for a model with no public element", () => {
    const { text } = generate(`slice "Internal" {\n  ui Screen @Customer\n  command Do Thing { a: string }\n  event Thing Done @Domain { a: string }\n}\n`);
    expect(text.trim().endsWith("namespace EventModel {}")).toBe(true);
  });

  it("includes a public command as an op — and no longer pulls in a non-public command beside a public event", () => {
    const { text } = generate(`
slice "S" {
  command Do Thing public { a: string }
  command Other Thing { b: string }
  event Thing Done @Domain public { a: string }
}
`);
    expect(text).toContain("interface Commands {\n    op doThing(a: string): void;\n  }");
    expect(text).not.toContain("otherThing");
    expect(text).toContain("model ThingDone {");
  });

  it("includes a public view as a model plus a no-arg accessor op", () => {
    const { text } = generate(`
slice "Emit" {
  command Do Thing
  event Thing Done @Domain
}
slice "Read It" {
  view Things public from "Thing Done" { a: string }
}
`);
    expect(text).toContain("model Things {");
    expect(text).toContain("op getThings(): Things;");
    expect(text).not.toContain("interface Commands");
  });

  it("folds a repeated public view instance (`again`) into its first declaration", () => {
    const { text } = generate(`
slice "First" {
  command Do Thing
  event Thing Done @Domain
}
slice "V1" {
  view Board public from "Thing Done" { a: string }
}
slice "V2" {
  view Board public again from "Thing Done"
}
`);
    expect((text.match(/model Board \{/g) ?? []).length).toBe(1);
  });

  it("puts the consumer-tolerance sentence on every generated model, declared types included", () => {
    const { text } = generate(`
type Money2 { cents: long }
slice "S" {
  command Do Thing
  event Thing Done @Domain public { a: Money2 }
}
`);
    const models = text.match(/model \w+/g) ?? [];
    expect(models).toEqual(["model Money2", "model ThingDone"]);
    expect(text.split(CONSUMER_TOLERANCE_SENTENCE).length - 1).toBe(2);
  });
});

describe("fixed public type table (R7)", () => {
  it("maps exactly the eleven table entries, case-insensitively", () => {
    expect(PUBLIC_SCALAR_TYPES).toEqual({
      string: "string",
      text: "string",
      int: "int32",
      long: "int64",
      decimal: "decimal",
      boolean: "boolean",
      uuid: "string",
      date: "plainDate",
      datetime: "utcDateTime",
      duration: "duration",
      bytes: "bytes",
    });
    const { text } = generate(`
slice "S" {
  command Do Thing
  event Thing Done @Domain public {
    a: String
    b: TEXT
    c: int
    d: long
    e: decimal
    f: boolean
    g: UUID
    h: Date
    i: DateTime
    j: duration
    k: bytes
    l: uuid[]
  }
}
`);
    for (const line of [
      "a: string;", "b: string;", "c: int32;", "d: int64;", "e: decimal;", "f: boolean;",
      "g: string;", "h: plainDate;", "i: utcDateTime;", "j: duration;", "k: bytes;", "l: string[];",
    ]) {
      expect(text).toContain(line);
    }
  });

  it("maps a declared type reference (bare and array) to its generated model, reachable types only", () => {
    const { text } = generate(`
type Used { x: string }
type Unused { y: string }
slice "S" {
  command Do Thing
  event Thing Done @Domain public {
    a: Used
    b: Used[]
  }
}
`);
    expect(text).toContain("a: Used;");
    expect(text).toContain("b: Used[];");
    expect(text).not.toContain("model Unused");
  });

  it("refuses (throws) rather than falling back to `unknown` when handed an unvalidated model", () => {
    expect(() => generate(`slice "S" {\n  event Thing Done @Domain public { a: Money }\n}`)).toThrow(/public-field-type-unresolved/);
  });
});

describe("optional fields (R8)", () => {
  it("emits `name?: T` on models and on command op parameters", () => {
    const { text } = generate(`
slice "S" {
  ui Screen @Customer
  command Place public {
    total: decimal
    note?: text
  }
  event Placed @Domain public {
    total: decimal
    note?: text
  }
}
`);
    expect(text).toContain("op place(total: decimal, note?: string): void;");
    expect(text).toContain("    note?: string;");
  });
});

describe("em-specific metadata becomes doc comments, never decorators", () => {
  it("records tags, renames and assigned as /** ... */ text", () => {
    const { text } = generate(`
slice "S" {
  command Do Thing
  event Thing Done renamed from "Thing Was Done" @Domain public {
    a: uuid tag
    b: string renamed from "oldB"
    c: datetime assigned
  }
  tag comboKey from a, b
}
`);
    expect(text).toContain("/** DCB identity tag */");
    expect(text).toContain("DCB composite tag `comboKey` from a, b");
    expect(text).toContain('renamed from "Thing Was Done"');
    expect(text).toContain('/** renamed from "oldB" */');
    expect(text).toContain("system-assigned — not supplied by the triggering command");
    expect(text).not.toMatch(/@tag\(|@assigned|@renamedFrom/i);
  });
});

describe("identifier shaping", () => {
  it("PascalCases names, dedupes collisions, backtick-quotes non-identifier field names", () => {
    const { text } = generate(`
slice "S1" {
  command Do The Thing public
  event Order Placed @Domain public { weird field: string }
}
slice "S2" {
  command Do Other Thing
  event order-placed @Domain public
}
`);
    expect(text).toContain("model OrderPlaced {");
    expect(text).toContain("model OrderPlaced_2 {}");
    expect(text).toContain("op doTheThing(): void;");
    expect(text).toContain("`weird field`: string;");
  });
});

describe("golden: examples/order-fulfillment", () => {
  it("generates the exact expected contract (public Order Placed / Open Orders)", () => {
    const src = readFileSync(EXAMPLE_PATH, "utf8");
    const { text } = generate(src, "examples/order-fulfillment/order-fulfillment.em");
    expect(text).toBe(`// GENERATED by em api generate — do not hand-edit.
// Source: examples/order-fulfillment/order-fulfillment.em
// Scope: the model's \`public\` commands (write API), events (async) and views (read API).

namespace OrderFulfillment {
  /**
   * Consumers tolerate unknown fields; additive changes do not break them.
   */
  model OrderPlaced {
    /** system-assigned — not supplied by the triggering command */
    orderId: string;
    customerId: string;
    total: decimal;
    /** system-assigned — not supplied by the triggering command */
    placedAt: utcDateTime;
  }

  /**
   * Consumers tolerate unknown fields; additive changes do not break them.
   */
  model OpenOrders {
    orderId: string;
    total: decimal;
    status: string;
  }

  interface Views {
    op getOpenOrders(): OpenOrders;
  }
}`);
  });

  it("is deterministic", () => {
    const src = readFileSync(EXAMPLE_PATH, "utf8");
    expect(generate(src, "x.em").text).toBe(generate(src, "x.em").text);
  });
});

describe("examples/multi-model: both models' committed contracts are current", () => {
  for (const key of ["checkout", "fulfillment"]) {
    it(`models/${key}/contracts/${key}.tsp equals a fresh generate`, () => {
      const file = join(MULTI, "models", key, `${key}.em`);
      const source = readFileSync(file, "utf8");
      const generated = generateContract(file, source, compile(source));
      expect(generated.contractPath).toBe(join(MULTI, "models", key, "contracts", `${key}.tsp`));
      expect(readFileSync(generated.contractPath, "utf8")).toBe(generated.text);
    });
  }
});

// ---- additive / breaking classification (R8) ------------------------------------------

const surface = (src: string) => {
  const c = compile(src);
  const doc = buildExportDoc(c.model, c.refs, c.diagnostics, src, "m.em").doc;
  return surfaceOf(doc.model.slices, doc.model.types);
};
const changes = (before: string, after: string) => diffSurfaces(surface(before), surface(after));
const ev = (fields: string) => `slice "S" {\n  command Do public { x: string }\n  event Done @D public { ${fields} }\n}\n`;
const cmd = (fields: string) => `slice "S" {\n  command Do public { ${fields} }\n  event Done @D\n}\n`;

describe("diffSurfaces", () => {
  it("output field removed = breaking; output field added (required or optional) = additive", () => {
    expect(changes(ev("a: string, b: string"), ev("a: string"))).toEqual([
      { kind: "breaking", element: "event.done", field: "b", what: "removed" },
    ]);
    expect(changes(ev("a: string"), ev("a: string, b: string, c?: string"))).toEqual([
      { kind: "additive", element: "event.done", field: "b", what: "added (required)" },
      { kind: "additive", element: "event.done", field: "c", what: "added (optional)" },
    ]);
  });

  it("output field required → optional = breaking; optional → required = breaking", () => {
    expect(changes(ev("a: string"), ev("a?: string"))).toEqual([
      { kind: "breaking", element: "event.done", field: "a", what: "changed required → optional" },
    ]);
    expect(changes(ev("a?: string"), ev("a: string"))).toEqual([
      { kind: "breaking", element: "event.done", field: "a", what: "changed optional → required" },
    ]);
  });

  it("command input: required field added = breaking, optional added = additive, required → optional = additive", () => {
    expect(changes(cmd("x: string"), cmd("x: string, y: string, z?: string"))).toEqual([
      { kind: "breaking", element: "command.do", field: "y", what: "added (required)" },
      { kind: "additive", element: "command.do", field: "z", what: "added (optional)" },
    ]);
    expect(changes(cmd("x: string"), cmd("x?: string"))).toEqual([
      { kind: "additive", element: "command.do", field: "x", what: "changed required → optional" },
    ]);
  });

  it("field renamed (`renamed from`) = breaking; type changed = breaking", () => {
    expect(changes(ev("a: string"), ev('b: string renamed from "a"'))).toEqual([
      { kind: "breaking", element: "event.done", field: "b", what: 'renamed from "a"' },
    ]);
    expect(changes(ev("a: string"), ev("a: int"))).toEqual([
      { kind: "breaking", element: "event.done", field: "a", what: "type changed string → int" },
    ]);
  });

  it("element added / marked public = additive; removed / renamed / `public` dropped = breaking", () => {
    const base = `slice "S" {\n  command Do public\n  event Done @D public\n}\n`;
    expect(changes(base, `slice "S" {\n  command Do public\n  event Done @D public\n  event Also @D public\n}\n`)).toEqual([
      { kind: "additive", element: "event.also", field: null, what: "added" },
    ]);
    expect(changes(`slice "S" {\n  command Do\n  event Done @D public\n}\n`, base)).toEqual([
      { kind: "additive", element: "command.do", field: null, what: "marked public" },
    ]);
    expect(changes(base, `slice "S" {\n  command Do public\n  event Done @D\n}\n`)).toEqual([
      { kind: "breaking", element: "event.done", field: null, what: "`public` dropped" },
    ]);
    expect(changes(base, `slice "S" {\n  command Do public\n}\n`)).toEqual([
      { kind: "breaking", element: "event.done", field: null, what: "removed" },
    ]);
    expect(changes(base, `slice "S" {\n  command Do public\n  event Finished renamed from "Done" @D public\n}\n`)).toEqual([
      { kind: "breaking", element: "event.finished", field: null, what: 'renamed from "Done"' },
    ]);
  });

  it("diffs declared types reachable from the public surface", () => {
    const t = (fields: string) => `type Money2 { ${fields} }\nslice "S" {\n  command Do\n  event Done @D public { m: Money2 }\n}\n`;
    expect(changes(t("cents: long, cur: string"), t("cents: long"))).toEqual([
      { kind: "breaking", element: "type.money2", field: "cur", what: "removed" },
    ]);
  });

  it("a model absent at base reports every public element additive", () => {
    expect(diffSurfaces(null, surface(ev("a: string")))).toEqual([
      { kind: "additive", element: "command.do", field: null, what: "added" },
      { kind: "additive", element: "event.done", field: null, what: "added" },
    ]);
  });
});

// ---- CLI: generate / check / typespec alias --------------------------------------------

function tmpMultiModelRepo(): string {
  const dir = mkdtempSync(join(tmpdir(), "em-api-"));
  cpSync(MULTI, dir, { recursive: true });
  git(dir, "init", "-q");
  git(dir, "add", "-A");
  git(dir, "commit", "-q", "-m", "seed");
  return dir;
}

describe("em api generate / check (CLI)", () => {
  it("generate writes <model dir>/contracts/<key>.tsp, creating the dir; check reports current", () => {
    const dir = mkdtempSync(join(tmpdir(), "em-api-"));
    try {
      mkdirSync(join(dir, "m"));
      writeFileSync(join(dir, "m", "shop.em"), `model "Shop"\nslice "S" {\n  command Buy public { sku: string }\n  event Bought @D\n}\n`);
      const g = em(["api", "generate", "m/shop.em"], dir);
      expect(g.status).toBe(0);
      expect(g.stdout).toBe(`wrote ${join("m", "contracts", "shop.tsp")}\n`);
      expect(existsSync(join(dir, "m", "contracts", "shop.tsp"))).toBe(true);
      const c = em(["api", "check", "m/shop.em"], dir);
      expect(c.status).toBe(0);
      expect(c.stdout).toBe(`contract ${join("m", "contracts", "shop.tsp")} is current\n`);
      // Same text whichever cwd generated it.
      const fromInside = em(["api", "generate", "shop.em", "--stdout"], join(dir, "m"));
      expect(fromInside.stdout).toBe(readFileSync(join(dir, "m", "contracts", "shop.tsp"), "utf8"));
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("check exits 1 on a missing or stale contract and names the regenerate command", () => {
    const dir = mkdtempSync(join(tmpdir(), "em-api-"));
    try {
      writeFileSync(join(dir, "shop.em"), `model "Shop"\nslice "S" {\n  command Buy public { sku: string }\n  event Bought @D\n}\n`);
      const missing = em(["api", "check", "shop.em"], dir);
      expect(missing.status).toBe(1);
      expect(missing.stdout).toBe(`contract ${join("contracts", "shop.tsp")} is missing — run: em api generate shop.em\n`);
      em(["api", "generate", "shop.em"], dir);
      writeFileSync(join(dir, "contracts", "shop.tsp"), "// hand-edited\n");
      const stale = em(["api", "check", "shop.em", "--json"], dir);
      expect(stale.status).toBe(1);
      const doc = JSON.parse(stale.stdout);
      expect(doc).toMatchObject({ apiCheckSchemaVersion: API_CHECK_SCHEMA_VERSION, file: "shop.em", current: false, base: null, changes: [] });
      expect(Object.keys(doc)).toEqual(["apiCheckSchemaVersion", "generator", "file", "contractPath", "current", "base", "changes"]);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("generate refuses on a model with a public-field-type-unresolved error", () => {
    const dir = mkdtempSync(join(tmpdir(), "em-api-"));
    try {
      writeFileSync(join(dir, "shop.em"), `slice "S" {\n  command Buy public { sku: Sku }\n  event Bought @D\n}\n`);
      const r = em(["api", "generate", "shop.em"], dir);
      expect(r.status).toBe(1);
      expect(r.stderr).toContain('public command "Buy" field "sku" has type "Sku", which is not a public type');
      expect(r.stderr).toContain("not generating: fix the errors above");
      expect(existsSync(join(dir, "contracts"))).toBe(false);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("check --base on a seeded field removal in examples/multi-model reports breaking (annotation only: exit 0 once regenerated)", () => {
    const dir = tmpMultiModelRepo();
    try {
      const file = "models/checkout/checkout.em";
      const p = join(dir, file);
      const before = readFileSync(p, "utf8");
      const seeded = before.replace("    total: decimal\n    placedAt", "    placedAt");
      expect(seeded).not.toBe(before);
      writeFileSync(p, seeded);
      const stale = em(["api", "check", file, "--base", "HEAD"], dir);
      expect(stale.status).toBe(1);
      expect(stale.stdout).toContain("is stale");
      expect(stale.stdout).toContain('breaking: event.order-submitted field "total" removed');
      expect(em(["api", "generate", file], dir).status).toBe(0);
      const ok = em(["api", "check", file, "--base", "HEAD"], dir);
      expect(ok.status).toBe(0);
      expect(ok.stdout).toBe(
        `contract ${join("models/checkout", "contracts", "checkout.tsp")} is current\n` +
          'breaking: event.order-submitted field "total" removed\n',
      );
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("an internal-only edit to a multi-model example keeps the committed contract current (no regenerate needed)", () => {
    const dir = tmpMultiModelRepo();
    try {
      const file = "models/checkout/checkout.em";
      const p = join(dir, file);
      const contract = join(dir, "models/checkout/contracts/checkout.tsp");
      const before = readFileSync(contract, "utf8");
      writeFileSync(p, readFileSync(p, "utf8").replace("  command Submit Order {\n", "  command Submit Order {\n    couponCode?: Coupon\n"));
      const r = em(["api", "check", file, "--base", "HEAD"], dir);
      expect(r.status).toBe(0);
      expect(r.stdout).toBe(`contract ${join("models/checkout", "contracts", "checkout.tsp")} is current\nno public-surface changes since HEAD\n`);
      expect(em(["api", "generate", file], dir).status).toBe(0);
      expect(readFileSync(contract, "utf8")).toBe(before);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("check --base where the model did not exist yet reports every public element additive", () => {
    const dir = tmpMultiModelRepo();
    try {
      mkdirSync(join(dir, "models", "billing"));
      writeFileSync(join(dir, "models", "billing", "billing.em"), `model "Billing"\nslice "S" {\n  command Bill public { amount: decimal }\n  event Billed @D\n}\n`);
      em(["api", "generate", "models/billing/billing.em"], dir);
      const r = em(["api", "check", "models/billing/billing.em", "--base", "HEAD", "--json"], dir);
      expect(r.status).toBe(0);
      expect(JSON.parse(r.stdout).changes).toEqual([{ kind: "additive", element: "command.bill", field: null, what: "added" }]);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("check --base refuses an unknown revision", () => {
    const dir = tmpMultiModelRepo();
    try {
      const r = em(["api", "check", "models/checkout/checkout.em", "--base", "no-such-rev"], dir);
      expect(r.status).toBe(1);
      expect(r.stderr).toContain('em api check: unknown revision "no-such-rev" (needed for --base)');
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  it("`em typespec` is a deprecated alias of `em api generate --stdout`", () => {
    const r = em(["typespec", "examples/order-fulfillment/order-fulfillment.em"], ROOT);
    expect(r.status).toBe(0);
    expect(r.stderr).toContain("warn: em typespec is deprecated — use em api generate");
    const g = em(["api", "generate", "examples/order-fulfillment/order-fulfillment.em", "--stdout"], ROOT);
    expect(r.stdout).toBe(g.stdout);
  });
});

// ---- Optional compile-verification (skip-if-absent) ------------------------------------
//
// `@typespec/compiler` is a devDependency only; it needs Node >= its own `engines.node`
// (CI runs Node 20), so this block skips rather than fails when that isn't met.
const TSP_BIN = join(ROOT, "node_modules", ".bin", "tsp");

function nodeSatisfiesEngineRequirement(pkgDir: string): boolean {
  try {
    const pkg = JSON.parse(readFileSync(join(pkgDir, "package.json"), "utf8")) as { engines?: { node?: string } };
    const required = pkg.engines?.node;
    const minMajor = required ? Number(required.match(/(\d+)/)?.[1] ?? 0) : 0;
    return Number(process.versions.node.split(".")[0]) >= minMajor;
  } catch {
    return false;
  }
}

const TSP_AVAILABLE = existsSync(TSP_BIN) && nodeSatisfiesEngineRequirement(join(ROOT, "node_modules", "@typespec", "compiler"));

function tspCompile(text: string): { status: number | null; out: string } {
  const dir = mkdtempSync(join(tmpdir(), "em-tsp-"));
  try {
    const file = join(dir, "main.tsp");
    writeFileSync(file, text);
    const res = spawnSync(process.execPath, [TSP_BIN, "compile", file, "--no-emit"], { encoding: "utf8" });
    return { status: res.status, out: `${res.stdout ?? ""}\n${res.stderr ?? ""}` };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

describe.skipIf(!TSP_AVAILABLE)("compiles with @typespec/compiler", () => {
  it("the order-fulfillment contract and both multi-model contracts compile", () => {
    const texts = [
      generate(readFileSync(EXAMPLE_PATH, "utf8")).text,
      readFileSync(join(MULTI, "models/checkout/contracts/checkout.tsp"), "utf8"),
      readFileSync(join(MULTI, "models/fulfillment/contracts/fulfillment.tsp"), "utf8"),
    ];
    for (const t of texts) {
      const { status, out } = tspCompile(t);
      expect(status, `tsp compile failed:\n${out}`).toBe(0);
    }
  });

  it("a fixture with declared types, optional fields, tags, renames and every table scalar compiles", () => {
    const { text } = generate(`
type Money2 {
  cents: long
  currency: string
}
slice "Do Widget Thing" {
  ui Admin Screen @Admin
  command Do Widget Thing public renamed from "Old Widget Thing" {
    widgetId: uuid
    amount: Money2
    memo?: text
  }
  event Widget Thinged @Widget public renamed from "Widget Old Thinged" {
    widgetId: uuid tag
    amount: Money2
    createdAt: datetime assigned
    on: date
    took: duration
    blob?: bytes
    count: int
    ok: boolean
    big: decimal
    tags: string[]
  }
  tag widgetComposite from widgetId, amount
}
slice "View Widgets" {
  view Widget List public from "Widget Thinged" {
    widgetId: uuid
    amount: Money2
  }
}
`);
    const { status, out } = tspCompile(text);
    expect(status, `tsp compile failed:\n${out}`).toBe(0);
  });
});
