// SPDX-License-Identifier: MIT
// `em api generate` (MIL-237, promoted from the MIL-159 `em typespec` POC): the model-owned
// contract for a model's `public` surface, as TypeSpec (https://typespec.io) source text —
// plain `model`/`interface`/`op` declarations, core scalars only, no imports, no decorators,
// no `@versioned` (one release train; versions are Backlog).
//
//  - public commands -> `interface Commands { op <name>(<params>): void; }` (the write API)
//  - public events   -> `model` (async payloads)
//  - public views    -> `model` + `interface Views { op get<View>(): <View>; }` (the read API)
//  - declared `type`s reachable from any of those -> `model`
//
// Types map through ONE fixed table (`PUBLIC_SCALAR_TYPES`, src/model/model.ts — briefing R7)
// or a declared `type`; there is no alias map, no generic-wrapper handling and no `unknown`
// fallback. `em validate`'s `public-field-type-unresolved` guarantees every field on this
// surface resolves, and the CLI refuses to generate from a model with errors, so an
// unresolvable type here is a programming error, not a user-facing case.
//
// Reuses `buildExportDoc` (emit/json.ts) so `public`/`optional`/`typeRef`/tags/renamedFrom are
// resolved once, the same way `em export` resolves them. Deterministic: no timestamps, no git
// data, no absolute paths — the `Source:` line is whatever label the caller passes (the CLI
// passes the model path relative to the contract file's own directory). Deliberately NO source
// hash (R12 amended): the text depends only on the public surface, so an internal-only `.em`
// edit leaves the contract byte-identical and neither CODEOWNERS routing nor the API-first
// gate fires on it.

import { NormalizedModel, resolvePublicType } from "../model/model.js";
import { RefsResult } from "../model/refs.js";
import { Diagnostic } from "../model/validate.js";
import { dedupe } from "../util/slug.js";
import { buildExportDoc, ElementExport, FieldExport } from "./json.js";

/** The sentence every generated `model` carries (MIL-239 relies on it verbatim). */
export const CONSUMER_TOLERANCE_SENTENCE = "Consumers tolerate unknown fields; additive changes do not break them.";

export const API_HEADER_LINE = "// GENERATED by em api generate — do not hand-edit.";

export interface ApiContractResult {
  /** TypeSpec source text, no trailing newline. */
  text: string;
  /** Same diagnostics `buildExport` would raise for this model. */
  diagnostics: Diagnostic[];
}

/** em element/type names are free text; TypeSpec model/interface names are PascalCase. */
function pascalCase(name: string): string {
  const words = name.match(/[A-Za-z0-9]+/g) ?? [];
  const joined = words.map((w) => w[0].toUpperCase() + w.slice(1)).join("");
  if (joined.length === 0) return "Unnamed";
  return /^[0-9]/.test(joined) ? `_${joined}` : joined;
}

function camelCase(pascal: string): string {
  return pascal.length > 0 ? pascal[0].toLowerCase() + pascal.slice(1) : pascal;
}

/** A field name that isn't a bare TypeSpec identifier is backtick-quoted (TypeSpec's own escape). */
function fieldIdentifier(name: string): string {
  if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)) return name;
  return "`" + name.replace(/\\/g, "\\\\").replace(/`/g, "\\`") + "`";
}

// `tag`, `renamed from` and `assigned` are modeling concerns, not wire shape — carried as doc
// comments, never decorators (a decorator would need its own TypeSpec library).
function fieldNotes(f: FieldExport): string | null {
  const notes: string[] = [];
  if (f.tag) notes.push("DCB identity tag");
  if (f.renamedFrom && f.renamedFrom.length > 0) {
    notes.push(`renamed from ${f.renamedFrom.map((n) => JSON.stringify(n)).join(", ")}`);
  }
  if (f.assigned) notes.push("system-assigned — not supplied by the triggering command");
  return notes.length > 0 ? notes.join("; ") : null;
}

function elementNotes(el: ElementExport): string[] {
  const notes: string[] = [];
  if (el.renamedFrom && el.renamedFrom.length > 0) {
    notes.push(`renamed from ${el.renamedFrom.map((n) => JSON.stringify(n)).join(", ")}`);
  }
  for (const t of el.tags ?? []) {
    if (t.kind === "composite") notes.push(`DCB composite tag \`${t.key}\` from ${(t.fields ?? []).join(", ")}`);
    else if (t.kind === "external") notes.push(`DCB external tag \`${t.key}\`: ${t.description}`);
  }
  return notes;
}

/** MIL-265: a public element's model-declared invariants, one `/** INV-X: rule *\/` line each in
 *  declaration order — part of the contract, so tightening a rule changes the committed file
 *  (and `em api check` annotates it). A `*\/` inside the rule text is escaped so the comment
 *  cannot close early. */
function invariantLines(el: ElementExport): string[] {
  return (el.invariants ?? []).map((inv) =>
    inv.rule === null ? `/** ${inv.id} */` : `/** ${inv.id}: ${inv.rule.replace(/\*\//g, "*\\/")} */`,
  );
}

function indent(lines: string[], depth: number): string[] {
  const pad = "  ".repeat(depth);
  return lines.map((l) => (l.length > 0 ? pad + l : l));
}

/** The public elements `em api` covers, in export (timeline) order. A repeated view
 *  (`view X again`) contributes its first public instance only — one logical read model,
 *  one TypeSpec declaration. Shared with `em api check` so both read the same surface. */
export function publicSurfaceOf(slices: { elements: ElementExport[] }[]): {
  commands: ElementExport[];
  events: ElementExport[];
  views: ElementExport[];
} {
  const commands: ElementExport[] = [];
  const events: ElementExport[] = [];
  const views: ElementExport[] = [];
  const seenViews = new Set<string>();
  for (const slice of slices) {
    for (const el of slice.elements) {
      if (!el.public) continue;
      if (el.kind === "command") commands.push(el);
      else if (el.kind === "event") events.push(el);
      else if (el.kind === "view") {
        const key = el.name.trim().toLowerCase();
        if (seenViews.has(key)) continue;
        seenViews.add(key);
        views.push(el);
      }
    }
  }
  return { commands, events, views };
}

/**
 * Build the `em api generate` contract text. Same parameter contract as `buildExport`
 * (already-validated, error-free model; `path` is the `.em` file's real path, used for the doc
 * join); `sourceLabel` is the `Source:` line's path (defaults to `path`).
 */
export function buildApiContract(
  model: NormalizedModel,
  refs: RefsResult,
  diagnostics: Diagnostic[],
  source: string,
  path: string,
  sourceLabel: string = path,
): ApiContractResult {
  const { doc, diagnostics: allDiagnostics } = buildExportDoc(model, refs, diagnostics, source, path);
  const typesByRef = new Map(doc.model.types.map((t) => [t.ref, t]));
  const surface = publicSurfaceOf(doc.model.slices);

  // Declared types reachable (transitively) from a public element's fields.
  const reachable = new Set<string>();
  const walk = (fields: FieldExport[] | null) => {
    for (const f of fields ?? []) {
      if (f.typeRef && !reachable.has(f.typeRef.ref)) {
        reachable.add(f.typeRef.ref);
        walk(typesByRef.get(f.typeRef.ref)?.fields ?? null);
      }
    }
  };
  for (const el of [...surface.commands, ...surface.events, ...surface.views]) walk(el.fields);

  const usedNames = new Set<string>();
  const typeNameByRef = new Map<string, string>();
  for (const t of doc.model.types) {
    if (reachable.has(t.ref)) typeNameByRef.set(t.ref, dedupe(pascalCase(t.name), usedNames, "_"));
  }

  const fieldType = (f: FieldExport, owner: string): string => {
    if (f.typeRef) {
      const name = typeNameByRef.get(f.typeRef.ref) ?? pascalCase(f.typeRef.name);
      return f.typeRef.array ? `${name}[]` : name;
    }
    const r = resolvePublicType(f.type ?? undefined, model.typesByName);
    if (!r || r.kind !== "scalar") {
      throw new Error(
        `em api generate: ${owner} field "${f.name}" has no public type — em validate's public-field-type-unresolved should have refused this model`,
      );
    }
    return r.array ? `${r.tsType}[]` : r.tsType;
  };

  const member = (f: FieldExport, owner: string) =>
    `${fieldIdentifier(f.name)}${f.optional ? "?" : ""}: ${fieldType(f, owner)}`;

  const docBlock = (notes: string[]): string[] => ["/**", ...notes.map((n) => ` * ${n}`), " */"];

  const renderModel = (
    name: string,
    fields: FieldExport[] | null,
    owner: string,
    notes: string[],
    invariants: string[] = [],
  ): string => {
    const lines = docBlock([CONSUMER_TOLERANCE_SENTENCE, ...notes]);
    const body: string[] = [...invariants];
    for (const f of fields ?? []) {
      const n = fieldNotes(f);
      if (n) body.push(`/** ${n} */`);
      body.push(`${member(f, owner)};`);
    }
    lines.push(body.length > 0 ? `model ${name} {` : `model ${name} {}`);
    if (body.length > 0) lines.push(...indent(body, 1), "}");
    return lines.join("\n");
  };

  const sections: string[] = [];

  const typeBlocks: string[] = [];
  for (const t of doc.model.types) {
    const name = typeNameByRef.get(t.ref);
    if (name) typeBlocks.push(renderModel(name, t.fields, `type "${t.name}"`, []));
  }
  if (typeBlocks.length > 0) sections.push(typeBlocks.join("\n\n"));

  const eventBlocks: string[] = [];
  for (const el of surface.events) {
    const name = dedupe(pascalCase(el.name), usedNames, "_");
    eventBlocks.push(renderModel(name, el.fields, `event "${el.name}"`, elementNotes(el), invariantLines(el)));
  }
  if (eventBlocks.length > 0) sections.push(eventBlocks.join("\n\n"));

  const viewBlocks: string[] = [];
  const viewOps: string[] = [];
  for (const el of surface.views) {
    const name = dedupe(pascalCase(el.name), usedNames, "_");
    viewBlocks.push(renderModel(name, el.fields, `view "${el.name}"`, elementNotes(el), invariantLines(el)));
    viewOps.push(`op get${name}(): ${name};`);
  }
  if (viewBlocks.length > 0) {
    sections.push(viewBlocks.join("\n\n"));
    sections.push(["interface Views {", ...indent(viewOps, 1), "}"].join("\n"));
  }

  const opNames = new Set<string>();
  const commandOps: string[] = [];
  for (const el of surface.commands) {
    const opName = dedupe(camelCase(pascalCase(el.name)), opNames, "_");
    const notes = elementNotes(el);
    if (notes.length > 0) commandOps.push(`/** ${notes.join("; ")} */`);
    commandOps.push(...invariantLines(el));
    const params = (el.fields ?? []).map((f) => {
      const n = fieldNotes(f);
      const line = member(f, `command "${el.name}"`);
      return n ? `/** ${n} */ ${line}` : line;
    });
    commandOps.push(`op ${opName}(${params.join(", ")}): void;`);
  }
  if (commandOps.length > 0) sections.push(["interface Commands {", ...indent(commandOps, 1), "}"].join("\n"));

  const namespaceName = pascalCase(doc.model.name ?? "Model");
  const header = [
    API_HEADER_LINE,
    `// Source: ${sourceLabel}`,
    "// Scope: the model's `public` commands (write API), events (async) and views (read API).",
  ];
  const body = sections.length > 0 ? indent(sections.join("\n\n").split("\n"), 1) : [];
  const ns = body.length > 0 ? [`namespace ${namespaceName} {`, ...body, "}"] : [`namespace ${namespaceName} {}`];
  return { text: [...header, "", ...ns].join("\n"), diagnostics: allDiagnostics };
}
